const specialtyCategories = [
  "Internal Medicine",
  "Surgical Specialties",
  "Pediatrics",
  "Obstetrics & Gynecology (OB-GYN)",
  "Psychiatry & Mental Health",
  "Diagnostic & Laboratory Medicine",
  "Emergency & Critical Care",
  "Anesthesiology",
  "Dermatology",
  "Neurology & Neurosurgery",
  "Orthopedics & Musculoskeletal",
  "Ophthalmology",
  "Otolaryngology (ENT)",
  "Cardiology & Cardiothoracic Surgery",
  "Gastroenterology & Hepatology",
  "Nephrology & Urology",
  "Pulmonology & Respiratory Medicine",
  "Endocrinology & Metabolism",
  "Hematology & Oncology",
  "Rehabilitation & Physical Medicine",
  "Infectious Disease & Tropical Medicine",
  "Preventive & Community Medicine",
  "Geriatrics",
  "Allergy & Immunology",
  "Genetics & Genomic Medicine",
  "Public Health & Health Administration",
  "Dentistry & Oral Surgery"
];

const getRandomSpecialty = () =>
  specialtyCategories[Math.floor(Math.random() * specialtyCategories.length)];

const dummyDoctors = [
  // ---- Already existing 10 doctors here ----

  {
    name: "Dr. Priya Menon",
    email: "priya.menon@example.com",
    rating: 4.6,
    Experience: "14 years",
    fees: 950,
    aboutMe: "Experienced cardiologist specializing in preventive heart care.",
    phoneNumber: 9823344556,
    availAppoint: {},
    clinicName: "Heart Care Institute",
    clinicCord: { lon: 76.2711, lat: 9.9312 },
    Speciality: getRandomSpecialty(),
    practice_Size: 8,
    qualification: "MBBS, DM Cardiology",
    address: "MG Road, Kochi",
    opendays: { startDay: "Mon", endDay: "Sat" },
    workinghrs: { startTime: "09:00", endTime: "17:00" },
    Reviews: [],
    Owner: null
  },
  {
    name: "Dr. Vikram Chatterjee",
    email: "vikram.chatterjee@example.com",
    rating: 4.3,
    Experience: "9 years",
    fees: 750,
    aboutMe: "ENT specialist treating hearing loss and sinus issues.",
    phoneNumber: 9834456677,
    availAppoint: {},
    clinicName: "Ear Nose Throat Clinic",
    clinicCord: { lon: 88.3639, lat: 22.5726 },
    Speciality: getRandomSpecialty(),
    practice_Size: 3,
    qualification: "MBBS, MS ENT",
    address: "Park Street, Kolkata",
    opendays: { startDay: "Tue", endDay: "Sun" },
    workinghrs: { startTime: "10:30", endTime: "16:30" },
    Reviews: [],
    Owner: null
  },
  {
    name: "Dr. Anjali Deshpande",
    email: "anjali.deshpande@example.com",
    rating: 4.7,
    Experience: "12 years",
    fees: 900,
    aboutMe: "Oncologist dedicated to cancer prevention and treatment.",
    phoneNumber: 9812233445,
    availAppoint: {},
    clinicName: "Hope Oncology Center",
    clinicCord: { lon: 73.8567, lat: 18.5204 },
    Speciality: getRandomSpecialty(),
    practice_Size: 5,
    qualification: "MBBS, DM Oncology",
    address: "JM Road, Pune",
    opendays: { startDay: "Mon", endDay: "Fri" },
    workinghrs: { startTime: "09:00", endTime: "18:00" },
    Reviews: [],
    Owner: null
  },
  {
    name: "Dr. Sameer Qureshi",
    email: "sameer.qureshi@example.com",
    rating: 4.5,
    Experience: "7 years",
    fees: 650,
    aboutMe: "Neurologist focusing on migraines and epilepsy treatment.",
    phoneNumber: 9877765432,
    availAppoint: {},
    clinicName: "Neuro Wellness Center",
    clinicCord: { lon: 72.8777, lat: 19.076 },
    Speciality: getRandomSpecialty(),
    practice_Size: 4,
    qualification: "MBBS, DM Neurology",
    address: "Andheri West, Mumbai",
    opendays: { startDay: "Wed", endDay: "Mon" },
    workinghrs: { startTime: "11:00", endTime: "19:00" },
    Reviews: [],
    Owner: null
  },
  {
    name: "Dr. Lakshmi Krishnan",
    email: "lakshmi.krishnan@example.com",
    rating: 4.9,
    Experience: "18 years",
    fees: 1300,
    aboutMe: "Renowned nephrologist treating chronic kidney diseases.",
    phoneNumber: 9822233344,
    availAppoint: {},
    clinicName: "Renal Health Clinic",
    clinicCord: { lon: 80.2707, lat: 13.0827 },
    Speciality: getRandomSpecialty(),
    practice_Size: 6,
    qualification: "MBBS, DM Nephrology",
    address: "Adyar, Chennai",
    opendays: { startDay: "Mon", endDay: "Sat" },
    workinghrs: { startTime: "09:30", endTime: "17:30" },
    Reviews: [],
    Owner: null
  }
];


module.exports=dummyDoctors;